name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false # we have timing issues on some OS, so we want them all to run
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
            show-progress: false
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          dotnet-version: |
            8.x
            9.x
      - name: Run build
        run: dotnet build -c Release src
      - name: Run tests
        run: dotnet test --logger GitHubActions
      - name: Run publish
        run: dotnet pack -o release src
      - name: Upload NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os }}
          path: release/
